---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Networking:
    - Pihole-1:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/pi-hole.svg
        href: https://10.10.10.110/admin      
    - Pihole-2:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/pi-hole.svg
        href: https://10.10.10.111/admin  
    - Nginx Proxy Manager:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/nginx-proxy-manager.svg
        href: https://10.10.10.102:81  

- Infrastructure:
    - Gateway:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/router.svg
        href: https://10.10.10.1
    - Proxmox:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/proxmox.svg
        href: https://10.10.10.100:8006
        widget:
            type: proxmox
            url: https://10.10.10.100:8006
            username: {{HOMEPAGE_VAR_PVE_USERNAME}}
            password: {{HOMEPAGE_VAR_PVE_PASSWORD}}

- Entertainment:
    - Jellyfin:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/jellyfin.svg
        href: https://10.10.10.120:8096    
    - Twitch:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/twitch.svg
        href: https://twitch.tv/ 
    - Youtube:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/youtube.svg
        href: https://youtube.com/

- Misc:
    - Calendar widget:
        widget:
            type: calendar
            firstDayInWeek: monday
            view: monthly 
            maxEvents: 10 
            showTime: true 
    - Stock widget:
        widget:
            type: stocks
            provider: finnhub
            showUSMarketStatus: true
            watchlist:
                - NVDA
                - IREN