---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Networking:
    - Pihole-1:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/pi-hole.svg
        href:        
    - Pihole-2:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/pi-hole.svg
        href: 
    - Nginx Proxy Manager:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/nginx-proxy-manager.svg
        href: 

- Infrastructure:
    - Gateway:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/router.svg
        href: 
    - Proxmox:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/proxmox.svg
        href: 
        widget:
            type: proxmox
            url: 
            username: {{HOMEPAGE_VAR_PVE_USERNAME}}
            password: {{HOMEPAGE_VAR_PVE_PASSWORD}}

- Entertainment:
    - Jellyfin:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/jellyfin.svg
        href:         
    - Twitch:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/twitch.svg
        href: https://twitch.tv/ 
    - Youtube:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/youtube.svg
        href: https://youtube.com/

- Calendar:
    widget:
        type: calendar
        firstDayInWeek: monday
        view: monthly 
        maxEvents: 10 
        showTime: true 
        # timezone:
        
- Stocks:
    widget:
        type: stocks
        provider: finnhub
        showUSMarketStatus: true
        watchlist:
            - NVDA
            - IREN