---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  finnhub: {{HOMEPAGE_VAR_FINNHUB}}

target: _self
headerStyle: clean
language: en

background:
    image: https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832_1280.jpg
    blur: xl
    brightness: 90
    opacity: 60 

layout:
  Networking:
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 2
  Entertainment:
    style: row
    columns: 3  
  Misc:
    style: row
    columns: 2